name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install libraries
        run: npm install

      - name: Build web app
        run: npm run build

      - name: Runs tests
        run: npm run test

      - name: Make the Electron app
        run: npm run make

      - name: Prepare artifacts
        run: |
          npx mkdir artifact
          npx mv out/make/*/*/*.exe out/make/*/*/*/*.zip out/make/*/*/*.rpm out/make/*/*/*.deb artifact/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: artifact