name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install libraries
        run: npm install

      - name: Build web app
        run: npm run build

      - name: Runs tests
        run: npm run test

      - name: Make the Electron app
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            out/make/squirrel.windows/x64/web-voting-1.0.0 Setup.exe
            out/make/zip/darwin/x64/web-voting-darwin-x64-1.0.0.zip
            out/make/rpm/x64/web-voting-1.0.0-1.x86_64.rpm
            out/make/deb/x64/web-voting_1.0.0_amd64.deb